---
project:
  type: website
  render:
    - "*.qmd"

website:
  title: My Presentations
  description: My Presentations
  site-path: ./
  site-url: https://adafede.github.io/my-presentations
  repo-url: https://github.com/adafede/my-presentations
  search:
    location: navbar
  navbar:
    right:
      - text: "![](https://codeberg.org/Codeberg/Design/raw/branch/main/logo/icon/svg/codeberg-logo_icon_white.svg)"
        aria-label: Codeberg
        href: https://codeberg.org/adafede/pages/my-presentations
  open-graph:
    locale: en
    site-name: https://adafede.github.io/my-presentations

format:
  html:
    grid:
      body-width: 1200px
    link-external-newwindow: true
    respect-user-color-scheme: true
    smooth-scroll: true

kernel: .venv
