---
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch: null
name: Publish
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: read
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  publish:
    runs-on: codeberg-small
    container:
      image: ghcr.io/mcanouil/quarto-codespaces:latest
    concurrency:
      group: altdoc-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # sudo apt-get install -y nasm libqpdf-dev libxslt1-dev
      - name: Install LaTeX dependencies
        run: |
          sudo tlmgr update --self
          # sudo tlmgr install caption fancyhdr ifmtarg koma-script moresize multirow wrapfig xifthen
      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('pak', repos = 'https://r-lib.github.io/p/pak/stable/')"
          # Rscript -e "pak::pkg_install(c('rmarkdown', 'knitr'))"
      - name: Build site
        run: |
          bash copy_dirs.sh
          uv run quarto render
          bash copy_dirs.sh
      - uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/my-presentations
          token: ${{ forge.token }}
          source: _site/